(()=>{
'use strict';
if(location.hostname!=='www.twitch.tv')return;
// A aba dedicada ao chat fica livre do painel para não cobrir o editor.
if(location.hostname==='www.twitch.tv'&&/^\/popout\/[a-z0-9_]+\/chat\/?$/i.test(location.pathname))return;
if(document.getElementById('companion-panel'))return;
const TEST_SEND=false; // Versão definitiva: exige cooldown disponível.
const {host,root}=CompanionPanelTemplate.createPanelHost();
document.documentElement.append(host);
const $=s=>root.querySelector(s);let state={},sending=false,displayedCatch=null,catchVisibleUntil=0;let expeditionData=null,expeditionBusy=false,expeditionAttemptAt=0,expeditionAttemptRod=null,expeditionMarkup='';
let invalid=false;
async function extensionCall(fn){
 try{if(!chrome.runtime.id)throw Error('Extension context invalidated');return await fn();}
 catch{invalid=true;state.enabled=false;state.result='Extensão atualizada. Recarregue esta página.';render();return {};}
}

function renderEvent(){const box=$('.event-data');if(!box)return;const event=state.event;box.replaceChildren();const text=document.createElement('div');text.textContent=event?.text||'Nenhum evento ativo no barco.';box.append(text);if(event&&Number.isFinite(event.seconds)){const time=document.createElement('p');time.style.margin='10px 0 0';time.style.fontVariantNumeric='tabular-nums';time.textContent=(state.enabled&&Date.now()-(event.at||0)<5000?'Tempo restante: ':'Último tempo lido: ')+Math.floor(event.seconds/60)+':'+String(event.seconds%60).padStart(2,'0');box.append(time);}}
function render(){renderTodayOverview();renderHomeOverview();renderStatusGoal();updateGoalNotice();if(workspace?.querySelector('.goal-overview'))workspace.querySelector('.balance')?.dispatchEvent(new Event('input'));updateExpeditions();$('.account').textContent=(state.user?'@'+state.user:'Conta pendente')+' · '+(state.boat||'faturetosl');renderEvent();const result=state.catchResult;const awaitingCatch=sending&&!result;if(result?.at&&result.at!==displayedCatch&&Date.now()-result.at<15000){displayedCatch=result.at;catchVisibleUntil=Date.now()+8000;}const notice=$('.catch-notice');if(notice){notice.hidden=!result||Date.now()>=catchVisibleUntil;if(!notice.hidden)notice.innerHTML=result.error?`<span>${esc(result.message||'Não foi possível pescar. Confira o chat.')}</span>`:result.caught?(result.image?`<img src="${result.image.replace(/"/g,'')}" alt="">`:'')+`<span>${String(result.name).replace(/[&<>]/g,'')} pescado!</span>`:'Não foi desta vez pescador.';}const fresh=Date.now()-(state.at||0)<5000;const ready=TEST_SEND?!sending&&Date.now()-(state.lastAttempt||0)>=15000:state.enabled&&fresh&&state.seconds===0&&!state.used&&!state.error&&!sending&&Date.now()-(state.lastAttempt||0)>=15000;
$('.switch').setAttribute('aria-checked',String(!!state.enabled));
$('.time').textContent=awaitingCatch?'Aguardando resposta':!state.enabled?'Pausado':!fresh&&!sending?'Conectando…':state.seconds===0?'Disponível':state.seconds===null?'Atenção':`${Math.floor(state.seconds/60)}:${String(state.seconds%60).padStart(2,'0')}`;
$('.status').textContent=(awaitingCatch?'Aguardando resposta da pesca.':null)||state.result||(TEST_SEND?'Modo de teste: cooldown não bloqueia o envio.':null)||(!state.enabled?'Ligue para acompanhar o cooldown.':!fresh?(state.monitorError||'Abra o inventário fixo e confira se o contador aparece.'):state.error|| (state.used?'Aguardando uma nova pesca.':'Atualizado a cada segundo.'));
$('header b').textContent=host.classList.contains('mini')?'Pesca · '+$('.time').textContent:'Pesca';
$('.fish').disabled=!ready;$('.fish').classList.toggle('waiting',!!state.enabled&&fresh&&state.seconds>0);$('.fish').classList.toggle('ready',TEST_SEND||!!ready);$('.fish-label').textContent=awaitingCatch?'Aguardando resposta':TEST_SEND?'Testar $pescar':state.enabled&&fresh&&state.seconds>0?'Aguardando cooldown':'Pescar';$('.fish').title=TEST_SEND?'Teste temporário: envio sem bloquear pelo cooldown':ready?'Pescar':!state.enabled?'Monitor desligado':$('.time').textContent;}
extensionCall(()=>chrome.storage.local.get('fishState')).then(s=>{if(!invalid)state=s.fishState||{};render();restoreBoat();});
chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.fishState){const previousBoat=state.boat||'faturetosl',previousUser=state.user||null;state=changes.fishState.newValue||{};render();if(previousBoat!==(state.boat||'faturetosl')||previousUser!==(state.user||null))restoreBoat();}});
$('.switch').onclick=()=>extensionCall(()=>chrome.runtime.sendMessage({type:'toggle',enabled:!state.enabled}));
const layoutKey='companionLayoutTwitch';
let layout={mini:false},drag=null,displayedMini=false;
function place(x,y){
 const r=root.querySelector('section').getBoundingClientRect();
 layout.x=Math.max(8,Math.min(x,Math.max(8,window.innerWidth-r.width-8)));
 layout.y=Math.max(8,Math.min(y,Math.max(8,window.innerHeight-(layout.mini?56:80))));
 root.querySelector('section').style.maxHeight=layout.mini?'48px':Math.max(64,window.innerHeight-layout.y-8)+'px';
 for(const [key,value] of Object.entries({position:'fixed',right:'auto',bottom:'auto',left:layout.x+'px',top:layout.y+'px',margin:'0',transform:'none'}))host.style.setProperty(key,value,'important');
}
function applyLayout(){
 if(displayedMini!==!!layout.mini){const previous=root.querySelector('section').getBoundingClientRect();layout.positions=layout.positions||{};layout.positions[displayedMini?'mini':'expanded']={x:previous.left,y:previous.top};const next=layout.positions[layout.mini?'mini':'expanded'];if(next){layout.x=next.x;layout.y=next.y;}else{layout.x=previous.left;layout.y=previous.top;}displayedMini=!!layout.mini;root.querySelector('section').scrollTop=0;}
 host.classList.toggle('mini',!!layout.mini);
 $('.collapse').textContent=layout.mini?'+':'−';
 $('.collapse').setAttribute('aria-label',layout.mini?'Expandir painel':'Minimizar painel');
 $('.collapse').setAttribute('aria-expanded',String(!layout.mini));
 if(Number.isFinite(layout.x)&&Number.isFinite(layout.y))place(layout.x,layout.y);
 render();
}
function saveLayout(){if(Number.isFinite(layout.x)&&Number.isFinite(layout.y)){layout.positions=layout.positions||{};layout.positions[layout.mini?'mini':'expanded']={x:layout.x,y:layout.y};}extensionCall(()=>chrome.storage.local.set({[layoutKey]:layout}));}
extensionCall(()=>chrome.storage.local.get(layoutKey)).then(v=>{layout=v[layoutKey]||layout;displayedMini=!!layout.mini;applyLayout();});
$('.expand-mini').onclick=()=>{layout.mini=false;applyLayout();saveLayout();};
$('.collapse').onclick=()=>{layout.mini=!layout.mini;applyLayout();saveLayout();};
host.addEventListener('contextmenu',e=>{if(!layout.mini)return;e.preventDefault();layout.mini=false;applyLayout();saveLayout();});
const header=$('header');
let suppressClickUntil=0;
// Captura dentro do painel para reconhecer elementos do Shadow DOM fechado.
function startPanelDrag(e){const path=e.composedPath();if(e.button!==0)return;if(layout.mini){if(path.includes($('.expand-mini')))return;}else if(!path.includes(header)||path.some(el=>el?.tagName==='BUTTON'))return;const r=root.querySelector('section').getBoundingClientRect();drag={startX:e.clientX,startY:e.clientY,dx:e.clientX-r.left,dy:e.clientY-r.top,moved:false};header.style.cursor='grabbing';if(!layout.mini)e.preventDefault();e.stopPropagation();}
function movePanelDrag(e){if(!drag)return;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4)drag.moved=true;if(!drag.moved)return;place(e.clientX-drag.dx,e.clientY-drag.dy);e.preventDefault();e.stopPropagation();}
function finishDrag(){if(!drag)return;if(drag.moved){suppressClickUntil=Date.now()+700;saveLayout();}drag=null;header.style.cursor='grab';}
root.addEventListener('mousedown',startPanelDrag,true);
// Preserva a rolagem nativa sem repassar a roda aos controles da Twitch.
root.addEventListener('wheel',e=>e.stopPropagation(),{passive:true});
window.addEventListener('mousemove',movePanelDrag,true);
window.addEventListener('mouseup',finishDrag,true);
window.addEventListener('blur',finishDrag);
// A tela cheia usa uma camada acima da página; z-index sozinho não basta.
function syncFullscreen(){try{const fullscreen=document.fullscreenElement;if(host.hasAttribute('popover')){if(host.matches(':popover-open'))host.hidePopover();host.removeAttribute('popover');}if(fullscreen){if(host.parentElement!==fullscreen)fullscreen.append(host);if(['VIDEO','IFRAME','CANVAS'].includes(fullscreen.tagName)&&typeof host.showPopover==='function'){host.setAttribute('popover','manual');host.showPopover();}else if(host.parentElement!==fullscreen)fullscreen.append(host);}else if(host.parentElement!==document.documentElement)document.documentElement.append(host);if(Number.isFinite(layout.x))place(layout.x,layout.y);}catch{if(!document.fullscreenElement&&host.parentElement!==document.documentElement)document.documentElement.append(host);}}
document.addEventListener('fullscreenchange',syncFullscreen);
syncFullscreen();
window.addEventListener('resize',()=>{if(Number.isFinite(layout.x)){place(layout.x,layout.y);saveLayout();}});

host.addEventListener('click',e=>{if(Date.now()<suppressClickUntil){e.preventDefault();e.stopImmediatePropagation();}},true);

$('.fish').onclick=async e=>{if(Date.now()<suppressClickUntil||!e.isTrusted||$('.fish').disabled)return;sending=true;render();try{await extensionCall(()=>chrome.runtime.sendMessage({type:'fish',id:crypto.randomUUID()}));}finally{sending=false;render();}};
$('.open-monitor').onclick=()=>extensionCall(()=>chrome.runtime.sendMessage({type:'openMonitor'}));

const scopedKey=key=>'boat:'+(state.boat||'faturetosl')+':' +(state.user||'unknown')+':'+key;
const scopedStorage={get:async key=>{const scoped=scopedKey(key);const result=await chrome.storage.local.get(scoped);return {[key]:result[scoped]};},set:async values=>chrome.storage.local.set(Object.fromEntries(Object.entries(values).map(([k,v])=>[scopedKey(k),v])))};
let shopBalances={};let lastReadAt=0;function headerRead(at){if(!Number.isFinite(at)||at<=0)return;lastReadAt=Math.max(lastReadAt,at);$('.read-stamp').textContent='Lido às '+new Date(lastReadAt).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo'});}
let savedGoal=null;
let profileData=null,shopItems=[],uiRevision=0,lastToday=null;let currentView='status',items=[],selected=new Set(),protectedNames=new Set(),snapshotAt=0,directSaleTotal=null,actionBusy=false;
const workspace=$('.workspace');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fishId=name=>name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[\s-]+/g,'_').replace(/[^a-z0-9_]/g,'');
async function api(message){const requestBoat=state.boat||'faturetosl';const r=await extensionCall(()=>chrome.runtime.sendMessage({...message,boat:requestBoat}));if((state.boat||'faturetosl')!==requestBoat)throw Error('O barco mudou durante a consulta.');if(r?.error)throw Error(r.error);headerRead(r?.at||r?.profile?.at||r?.today?.at);return r;}
function note(text){let n=workspace.querySelector('.notice');if(!n){n=document.createElement('p');n.className='notice';workspace.append(n);}n.textContent=text;}
async function perform(text){if(actionBusy)return;actionBusy=true;try{const r=await api({type:'command',command:text});if(text==='$hoje'){if(!r.sent)note(r.message||'A mensagem não foi enviada. Confira o campo do chat.');else if(r.today)showToday(r.today);else note('Resposta do resumo não encontrada em 15 segundos. Nenhum reenvio automático.');}else note(r.message||'Ação processada. Confira a resposta no chat.');}catch(e){note(e.message);}finally{actionBusy=false;}}
// Confirmação do resumo em diálogo, sem deslocar a tela.
function reviewToday(description){if(root.querySelector('.review-dialog'))return;const origin=root.activeElement;const dialog=document.createElement('dialog');dialog.className='review-dialog';dialog.setAttribute('aria-labelledby','today-confirm-title');dialog.setAttribute('aria-describedby','today-confirm-description');dialog.innerHTML=`<h3 id="today-confirm-title">Atualizar meu dia?</h3><p id="today-confirm-description">${esc(description)}</p><div class="tools"><button class="cancel" autofocus>Cancelar</button><button class="primary confirm">Confirmar e atualizar</button></div>`;let confirmed=false;dialog.addEventListener('close',()=>{dialog.remove();if(origin?.isConnected)origin.focus();if(confirmed)perform('$hoje');},{once:true});dialog.querySelector('.cancel').onclick=()=>dialog.close();dialog.querySelector('.confirm').onclick=()=>{confirmed=true;dialog.close();};root.append(dialog);dialog.showModal();}
function review(text,description){if(text==='$vender todos'){reviewSellAll();return;}if(text==='$hoje'){reviewToday(description);return;}workspace.querySelector('.review')?.remove();const box=document.createElement('div');box.className='review';box.innerHTML=`<b>Revisar ação</b><p>${esc(description)}</p><code>${esc(text)}</code><div class="tools"><button class="primary confirm">Confirmar e enviar</button><button class="cancel">Cancelar</button></div>`;workspace.append(box);
if(text.startsWith('$vender ')){const native=document.createElement('button');native.textContent='Abrir venda na Twish';native.className='primary';box.querySelector('.tools').prepend(native);box.querySelector('.confirm').textContent='Enviar venda no chat';native.onclick=async()=>{native.disabled=true;try{const id=text.split(' ')[1];if(id!=='todos'){const fish=items.find(x=>fishId(x.name)===id);if(!fish)throw Error('Atualize o inventário.');await api({type:'inspectFish',name:fish.name,market:false,refresh:true});}await api({type:'openMonitor'});note('Conclua a venda no inventário oficial. Nenhum comando enviado.');box.remove();}catch(e){note(e.message);native.disabled=false;}};}
box.querySelector('.cancel').onclick=()=>box.remove();box.querySelector('.confirm').onclick=async()=>{box.querySelector('.confirm').disabled=true;await perform(text);box.remove();};}
async function refresh(){try{workspace.querySelector('.notice')?.remove();const result=await api({type:'snapshot',refresh:true});items=result.fish||[];profileData=result.profile||profileData;snapshotAt=result.at;directSaleTotal=result.directSaleTotal??null;if(currentView==='inventario')drawInventory();}catch(e){note(e.message);}}
const rarity={common:'Comum',uncommon:'Incomum',rare:'Raro',epic:'Épico',legendary:'Lendário',mythic:'Mítico',mythical:'Mítico',secret:'Secreto'};
const fmt=n=>n===null||n===undefined?'Indisponível':Number(n).toLocaleString('pt-BR');
function sprite(fish){try{const u=new URL(fish.image);if(u.protocol==='https:'&&u.pathname.includes('/fish/'))return `<span class="sprite tier-${esc(fish.tier)}"><img src="${esc(u.href)}" alt="${esc(fish.name)}" loading="lazy" referrerpolicy="no-referrer"></span>`;}catch{}return '<span class="sprite empty" aria-hidden="true">◇</span>';}
const {reviewSellAll,drawInventory}=CompanionPanelInventory.create({root,workspace,api,note,review,esc,fmt,sprite,rarity,stateRef:()=>state,itemsRef:()=>items,selectedRef:()=>selected,protectedNamesRef:()=>protectedNames,currentViewRef:()=>currentView,directSaleTotalRef:()=>directSaleTotal,snapshotAtRef:()=>snapshotAt,getActionBusy:()=>actionBusy,setActionBusy:value=>{actionBusy=value;},uiRevisionRef:()=>uiRevision});

const {progress,renderStatusGoal,updateGoalNotice}=CompanionPanelProgress.create({root,workspace,extensionCall,scopedStorage,loadProfile,api,stateRef:()=>state,profileDataRef:()=>profileData,shopItemsRef:()=>shopItems,setShopItems:value=>{shopItems=value;},shopBalancesRef:()=>shopBalances,setShopBalances:value=>{shopBalances=value;},savedGoalRef:()=>savedGoal,setSavedGoal:value=>{savedGoal=value;},uiRevisionRef:()=>uiRevision,fmt,esc,note,review,renderTodayOverview});
function fishing(){workspace.innerHTML='<h3>Pronto para a próxima captura</h3><div class="tile equipment-card"><div class="metric"><span>Vara equipada</span><span>Consultar no inventário</span></div><div class="metric"><span>Isca</span><span>Consultar no inventário</span></div><div class="metric"><span>Anzol</span><span>Consultar no inventário</span></div></div>';renderEquipment();loadProfile(false).then(()=>{if(currentView==='pesca')renderEquipment();});}
function statusView(){workspace.innerHTML='<div class="status-dashboard"><div class="tile home-overview"><div class="status-balances"><div class="metric"><span>Twishcoins</span><b class="home-coins"></b></div><div class="metric"><span>Pérolas</span><b class="home-pearls"></b></div><div class="metric"><span>Escamas</span><b class="home-scales"></b></div></div><div class="status-inventory"><div><span>Peixes no inventário</span><div class="muted">Venda direta disponível</div></div><b><span class="home-inventory"></span> <small>twishcoins</small></b></div></div><div class="tile status-goal"><div class="muted">Minha próxima conquista</div><div class="metric"><b class="status-goal-name"></b><span class="status-goal-ratio"></span></div><progress class="status-goal-bar" value="0" max="100" aria-label="Progresso da meta"></progress><div class="muted status-goal-message"></div><div class="status-rod-trade muted" hidden></div></div><div class="tile boat-information"><div class="muted info-label">Evento do barco</div><div class="event-data"></div><div class="goal-notice" hidden></div><div class="expedition-summary"></div></div></div>';renderHomeOverview();renderStatusGoal();renderEvent();updateGoalNotice();updateExpeditions();}
async function loadProfile(show=true,refresh=false){const revision=uiRevision;try{const data=await api({type:'siteQuery',page:'profile',refresh});profileData=data.profile;renderHomeOverview();items=data.fish||[];snapshotAt=data.at;directSaleTotal=data.directSaleTotal??null;if(show&&revision===uiRevision)showProfile(refresh);return profileData;}catch(e){note(e.message);return null;}}
function renderTodayOverview(){const box=root.querySelector('.today-overview');if(!box)return;for(const key of ['casts','fish','misses'])box.querySelector('.home-'+key).textContent=lastToday?.[key]==null?'—':fmt(lastToday[key]);}
function renderHomeOverview(){const box=root.querySelector('.home-overview');if(!box)return;const values={coins:profileData?.coins??shopBalances.coins,pearls:profileData?.pearls??shopBalances.pearls,scales:shopBalances.scales,inventory:directSaleTotal};for(const [key,value] of Object.entries(values))box.querySelector('.home-'+key).textContent=value===null||value===undefined?'—':fmt(value);}
function currentRod(){return state.liveRod||profileData?.equipment?.find(e=>/^vara\b/i.test(e.name||''))?.name||null;}
function renderEquipment(){const tile=workspace.querySelector('.equipment-card');if(!tile||!profileData)return;tile.querySelectorAll('.metric').forEach(e=>e.remove());for(const eq of [...profileData.equipment].reverse()){const row=document.createElement('div');row.className='metric';row.innerHTML=`<span>${esc(eq.name||'Indisponível')}</span>${eq.image?`<img class="equipment-art" src="${esc(eq.image)}" alt="">`:eq.icon?`<span class="equipment-empty-icon" aria-hidden="true">${esc(eq.icon)}</span>`:''}`;tile.prepend(row);}headerRead(profileData.at);}
function showProfile(refresh=false){workspace.innerHTML=`<div class="heading-row"><h3>Meu perfil</h3><button class="reload-profile">Atualizar</button></div><div class="tile"><div class="metric"><span>Saldo</span><b>${fmt(profileData?.coins)} coins</b></div><div class="metric"><span>Pérolas</span><b>${fmt(profileData?.pearls)}</b></div><div class="metric"><span>Escamas</span><b class="scales-value">${fmt(shopBalances.scales)}</b></div><div class="metric"><span>Nível</span><b>${fmt(profileData?.level)}</b></div><div class="metric"><span>XP</span><b>${fmt(profileData?.xp)} / ${fmt(profileData?.xpTarget)}</b></div><div class="metric"><span>Pontos</span><b>${fmt(profileData?.points)}</b></div><p class="muted">Inventário do barco atual</p></div><div class="tile"><h4>Minha posição</h4>${(profileData?.ranks||[]).map(x=>`<div class="metric"><span>${esc(x.label)}</span><b>${esc(x.value)}</b></div>`).join('')}</div>`;workspace.querySelector('.reload-profile').onclick=()=>loadProfile(true,true);api({type:'siteQuery',page:'shop',refresh}).then(data=>{shopBalances=data.balances||{};const el=workspace.querySelector('.scales-value');if(el)el.textContent=fmt(shopBalances.scales);}).catch(e=>note(e.message));}
function showToday(data){lastToday=data;headerRead(data.at);renderTodayOverview();if(currentView==='status'&&workspace.querySelector('.home-overview')){renderHomeOverview();loadProfile(false,true).then(()=>{renderHomeOverview();renderStatusGoal();if(currentView==='pesca')renderEquipment();if(workspace.querySelector('.goal-overview'))workspace.querySelector('.balance')?.dispatchEvent(new Event('input'));});return;}if(workspace.querySelector('.goal-overview')){workspace.querySelector('.balance')?.dispatchEvent(new Event('input'));const revision=uiRevision;loadProfile(false,true).then(()=>{if(revision===uiRevision&&workspace.querySelector('.goal-overview'))workspace.querySelector('.balance')?.dispatchEvent(new Event('input'));});return;}workspace.innerHTML=`<div class="heading-row"><h3>Resumo do dia</h3><button class="update-today">Atualizar</button></div><div class="tile today-card"><div class="metric"><span>Lançadas</span><b>${fmt(data.casts)}</b></div><div class="metric"><span>Peixes</span><b>${fmt(data.fish)}</b></div><div class="metric"><span>Sem captura</span><b>${fmt(data.misses)}</b></div><p class="muted">Última consulta: ${esc(new Date(data.at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}))} · TwishGameBot</p></div>`;workspace.querySelector('.update-today').onclick=()=>review('$hoje','Atualizar o resumo no chat. O resultado anterior permanece salvo até receber uma nova resposta.');}

$('.tabs').onclick=e=>{const button=e.target.closest('[data-view]');if(!button)return;uiRevision++;currentView=button.dataset.view;root.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===button));({pesca:fishing,status:statusView,inventario:drawInventory,expedicoes:expeditions,progresso:progress})[currentView]();if(currentView==='inventario'&&state.enabled)refresh();};
chrome.storage.onChanged.addListener((changes,area)=>{const data=changes[scopedKey('companionSnapshot')]?.newValue;if(area!=='local'||!data)return;items=data.fish||[];snapshotAt=data.at;directSaleTotal=data.directSaleTotal??null;selected=new Set([...selected].filter(name=>items.some(f=>f.name===name)));if(currentView==='inventario'&&workspace.querySelector('.search')){const query=workspace.querySelector('.search').value;drawInventory();workspace.querySelector('.search').value=query;workspace.querySelector('.search').oninput();}renderHomeOverview();});
chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='local'||!changes[scopedKey('companionProfile')])return;profileData=changes[scopedKey('companionProfile')].newValue||null;headerRead(profileData?.at);if(currentView==='pesca'&&workspace.querySelector('.equipment-card'))renderEquipment();renderStatusGoal();updateGoalNotice();updateExpeditions();if(currentView==='progresso'&&workspace.querySelector('.balance')){const input=workspace.querySelector('.balance');input.value=profileData?.coins??'';input.dispatchEvent(new Event('input'));}});
chrome.storage.onChanged.addListener((changes,area)=>{const key=scopedKey('companionSiteProtected');if(area==='local'&&changes[key]){protectedNames=new Set(changes[key].newValue||[]);for(const name of protectedNames)selected.delete(name);if(currentView==='inventario'&&workspace.querySelector('.search')){const search=workspace.querySelector('.search').value;drawInventory();workspace.querySelector('.search').value=search;workspace.querySelector('.search').oninput();}}});

chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes[scopedKey('companionToday')]){lastToday=changes[scopedKey('companionToday')].newValue||lastToday;renderTodayOverview();renderHomeOverview();if(workspace.querySelector('.goal-overview'))workspace.querySelector('.balance')?.dispatchEvent(new Event('input'));}});


setInterval(()=>{if(state.enabled&&!invalid)extensionCall(()=>chrome.runtime.sendMessage({type:'monitorHealth'}));},5000);
chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='local')return;const goal=changes[scopedKey('companionGoal')];if(goal)savedGoal=goal.newValue||null;const balance=changes[scopedKey('companionShopBalances')];if(balance)shopBalances=balance.newValue||{};renderHomeOverview();renderStatusGoal();updateGoalNotice();if(workspace.querySelector('.goal-overview'))workspace.querySelector('.balance')?.dispatchEvent(new Event('input'));});

async function refreshExpeditions(force=false){const rod=currentRod();if(expeditionBusy||!state.enabled||!rod)return;const channel=state.boat||'faturetosl',account=state.user;expeditionBusy=true;expeditionAttemptAt=Date.now();expeditionAttemptRod=rod;try{const data=await api({type:'siteQuery',page:'expedicoes',refresh:force});if(channel===(state.boat||'faturetosl')&&account===state.user&&rod===currentRod()&&data.rod===rod){expeditionData=data;expeditionMarkup='';updateExpeditions();}}catch(e){if(force)note(e.message);}finally{expeditionBusy=false;updateExpeditions();}}
function expeditions(){workspace.innerHTML='<h3>Expedições</h3><p class="muted">Marés dos destinos liberados para sua vara.</p><div class="expedition-notice expedition-detail"></div>';expeditionMarkup='';updateExpeditions();if(state.enabled){const load=async()=>{if(!currentRod())await loadProfile(false);if(currentView!=='expedicoes'||expeditionBusy) return;if(currentRod())await refreshExpeditions(true);};load().catch(e=>note(e.message));}}
function updateExpeditions(){
 const box=$('.expedition-detail');const summary=$('.expedition-summary');
 const rod=currentRod();
 const valid=expeditionData&&expeditionData.day===CompanionExpeditions.day(Date.now())&&rod&&expeditionData.rod===rod;
 const fresh=Date.now()-(state.at||0)<5000&&!state.error;
 if((currentView==='expedicoes'||currentView==='status')&&state.enabled&&fresh&&rod&&!valid&&!expeditionBusy&&(expeditionAttemptRod!==rod||Date.now()-expeditionAttemptAt>60000))refreshExpeditions();
 const seas=valid?expeditionData.seas.filter(e=>e.accessible):[];
 if(!seas.length){expeditionMarkup='';if(summary){const text=valid?'Nenhuma expedição liberada para sua vara.':expeditionBusy?'Consultando a maré para sua vara…':rod?'Maré ainda não consultada.':'Aguardando identificar sua vara.';summary.innerHTML='<div class="muted info-label">Expedição</div><p>'+esc(text)+'</p>';}if(box){const text=valid?'Nenhuma expedição liberada para sua vara no cais.':expeditionBusy?'Consultando as marés…':!rod?'Aguardando identificar a vara equipada.':'Marés ainda não disponíveis para esta vara.';const markup='<p>'+esc(text)+'</p><div class="tools"><button class="expedition-refresh" '+(!state.enabled||!rod?'disabled':'')+'>Atualizar maré</button></div>';if(box.innerHTML!==markup){box.innerHTML=markup;box.querySelector('.expedition-refresh').onclick=()=>refreshExpeditions(true);}}return;}
 const rated=seas.map(sea=>({sea,rating:CompanionExpeditions.advice(sea)})).sort((a,b)=>{const starsA=a.rating?.stars??0,starsB=b.rating?.stars??0;if(starsB!==starsA)return starsB-starsA;return String(a.sea.name||'').localeCompare(String(b.sea.name||''),'pt-BR');});const best=rated.find(x=>x.rating)||rated[0];
 if(summary){summary.innerHTML='<div class="muted info-label">Expedições liberadas para sua vara</div><div class="muted">'+esc(rod)+(state.enabled&&fresh?'':' · última consulta')+'</div>'+rated.map(({sea,rating})=>'<div class="expedition-sea"><b>'+esc(sea.name)+'</b><div class="expedition-tide">'+esc(sea.tide||'Sem maré diária')+'</div><p class="muted">'+esc(rating?.text||'Este destino não tem maré diária; confira as condições no cais.')+'</p></div>').join(''); }
 if(!box)return;
 const heading=best?.rating?(best.rating.stars>=5?'Ótimo dia para buscar exclusivas':best.rating.stars>=4?'Há uma boa oportunidade de expedição':best.rating.stars<=2?'Hoje vale esperar uma maré melhor':'Maré para sua expedição'):'Expedições disponíveis para sua vara';
 const markup='<h4>'+esc(heading)+'</h4><div class="muted">'+esc(rod)+(state.enabled&&fresh?'':' · última consulta')+'</div>'+rated.map(({sea,rating})=>'<div class="expedition-sea"><b>'+esc(sea.name)+'</b>'+(rating?'<span class="expedition-stars" aria-label="'+rating.stars+' de 5 estrelas">'+'★'.repeat(rating.stars)+'☆'.repeat(5-rating.stars)+'</span>':'')+'<div class="expedition-tide">'+esc(sea.tide||'Sem maré diária')+(sea.effect?' · '+esc(sea.effect):'')+'</div><p>'+esc(rating?.text||'Este destino não participa da Maré do Dia. Confira os riscos no cais.')+'</p></div>').join('')+'<div class="tools"><button class="expedition-refresh" '+(!state.enabled?'disabled':'')+'>Atualizar maré</button><button class="expedition-open" '+(!state.enabled?'disabled':'')+'>Ver cais ↗</button></div>';
 if(markup===expeditionMarkup&&box.innerHTML)return;expeditionMarkup=markup;box.innerHTML=markup;box.querySelector('.expedition-refresh').onclick=()=>refreshExpeditions(true);box.querySelector('.expedition-open').onclick=()=>api({type:'openOfficial',page:'expedicoes'});
}
chrome.storage.onChanged.addListener((changes,area)=>{const key=scopedKey('query:expedicoes:');if(area==='local'&&changes[key]){expeditionData=changes[key].newValue||null;expeditionMarkup='';updateExpeditions();}});

async function restoreBoat(){const revision=++uiRevision;profileData=null;savedGoal=null;expeditionData=null;expeditionAttemptAt=0;expeditionAttemptRod=null;expeditionMarkup='';shopItems=[];shopBalances={};lastToday=null;items=[];selected=new Set();protectedNames=new Set();snapshotAt=0;directSaleTotal=null;lastReadAt=0;$('.read-stamp').textContent='Aguardando leitura';workspace.innerHTML='<p>Carregando dados deste barco…</p>';const boat=state.boat||'faturetosl',account=state.user;const keys=['companionProfile','companionSnapshot','companionToday','companionSiteProtected','companionShopBalances','companionGoal','query:expedicoes:'];const data=await chrome.storage.local.get(keys.map(scopedKey));if(revision!==uiRevision||boat!==(state.boat||'faturetosl')||account!==state.user)return;savedGoal=data[scopedKey('companionGoal')]||null;expeditionData=data[scopedKey('query:expedicoes:')]||null;profileData=data[scopedKey('companionProfile')]||null;const snapshot=data[scopedKey('companionSnapshot')];items=snapshot?.fish||[];snapshotAt=snapshot?.at||0;directSaleTotal=snapshot?.directSaleTotal??null;lastToday=data[scopedKey('companionToday')]||null;shopBalances=data[scopedKey('companionShopBalances')]||{};protectedNames=new Set(data[scopedKey('companionSiteProtected')]||[]);headerRead(Math.max(profileData?.at||0,snapshotAt,lastToday?.at||0));({pesca:fishing,status:statusView,inventario:drawInventory,expedicoes:expeditions,progresso:progress})[currentView]();if(state.enabled){try{if(currentView==='progresso'||currentView==='status'){const shop=await api({type:'siteQuery',page:'shop'});shopItems=shop.items||shopItems;shopBalances=shop.balances||shopBalances;renderHomeOverview();renderStatusGoal();updateGoalNotice();if(workspace.querySelector('.goal-overview'))workspace.querySelector('.balance')?.dispatchEvent(new Event('input'));}if(currentView==='inventario'&&!snapshot)await refresh();}catch(e){if(revision===uiRevision)note(e.message);}}}
setInterval(render,1000);
})();
