const projectRoot=require('path').resolve(__dirname,'..')+'/';
let shopReads=0,fishReply={caught:true,name:"Piau"};
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
let handler,next=20,alarmListener,resolveFish;const store={fishState:{enabled:false,boat:'faturetosl',user:'madtraxbr'}},session={},operations=[],keys=[];
const tabs=new Map([[1,{id:1,url:'https://www.twitch.tv/outrostreamer',active:true,status:'complete'}],[2,{id:2,url:'https://twish.com.br/c/faturetosl/shop',active:true,status:'complete'}]]);
const chrome={alarms:{create:()=>{},onAlarm:{addListener:f=>alarmListener=f}},permissions:{contains:async()=>true},debugger:{attach:async target=>{assert.equal(target.tabId,session.companionOwnedChatTab);},detach:async()=>{},sendCommand:async(target,method,data)=>{assert.equal(target.tabId,session.companionOwnedChatTab);keys.push(method);}},storage:{local:{get:async()=>structuredClone(store),set:async v=>Object.assign(store,structuredClone(v))},session:{get:async()=>({...session}),set:async v=>Object.assign(session,v),remove:async list=>{for(const k of Array.isArray(list)?list:[list])delete session[k];}}},runtime:{onMessage:{addListener:f=>handler=f},onStartup:{addListener:()=>{}},onInstalled:{addListener:()=>{}}},scripting:{executeScript:async()=>{}},tabs:{onRemoved:{addListener:()=>{}},onUpdated:{addListener:()=>{}},get:async id=>{if(!tabs.has(id))throw Error('Missing');return tabs.get(id);},create:async data=>{assert.equal(data.active,false);const tab={id:next++,status:'complete',...data};tabs.set(tab.id,tab);return tab;},update:async(id,data)=>{assert(id>=20);assert.notEqual(data.active,true,'Foreground activation during send');operations.push({id,...data});Object.assign(tabs.get(id),data);},reload:async id=>assert(id>=20),remove:async id=>{assert(id>=20);assert.equal(store.fishState.enabled,false);tabs.delete(id);},sendMessage:async(id,m)=>{
 if(m.type==='readerPing')return{alive:true};
 if(m.type==='readPage'&&m.page==='shop'){shopReads++;return{account:'madtraxbr',catalogVersion:2,items:[{name:'Vara Encantada',price:store.fishState.event?4800:6000,normalPrice:6000,currency:'coins'}],balances:{coins:1750,pearls:100,scales:7},at:Date.now()};}
 if(['probe','prepareNative','focusEditor','insertChatCommand','armFish','fishResult','armToday','todayResult','nativeStatus','submitNative','chatBottom'].includes(m.type))assert.equal(id,session.companionOwnedChatTab,'Personal chat used');
 if(m.type==='probe')return{ready:true};if(m.type==='prepareNative')return{x:10,y:10,hasCommand:true,focused:true};if(m.type==='focusEditor')return{focused:true};if(m.type==='insertChatCommand')return{hasCommand:true};if(m.type==='submitNative'){keys.push('submitNative');if(m.command==='$pescar')resolveFish({fish:fishReply?{...fishReply,at:Date.now()}:null});return{clicked:true};}if(m.type==='nativeStatus'){if(m.command==='$pescar'&&fishReply)assert.equal(store.fishState.catchResult?.name,'Piau','Captura deve estar publicada antes de confirmar o campo vazio');return{remains:false,cleared:true};}if(m.type==='awaitFishResult')return new Promise(resolve=>resolveFish=resolve);return{};
 }}};
vm.runInNewContext(fs.readFileSync(projectRoot+'background.js','utf8'),{chrome,Date,Number,URL,Promise,Error,setTimeout});const sender={url:tabs.get(1).url,tab:{id:1}};const send=(m,s=sender)=>new Promise(resolve=>handler(m,s,resolve));
(async()=>{
 await send({type:'monitorHealth'});assert.equal(tabs.size,2);
 await send({type:'toggle',enabled:true});assert.equal(tabs.size,4);const chatId=session.companionOwnedChatTab,monitorId=session.companionOwnedMonitorTab;
 assert.equal(tabs.get(chatId).muted,true);assert.equal(tabs.get(chatId).pinned,true);assert.equal(tabs.get(chatId).active,false);assert.match(tabs.get(chatId).url,/popout\/faturetosl\/chat/);
 delete session.companionOwnedChatTab;delete session.companionOwnedMonitorTab;await send({type:'monitorHealth'});assert.equal(tabs.size,4,'Reload must reuse owned tabs');assert.equal(session.companionOwnedChatTab,chatId);assert.equal(session.companionOwnedMonitorTab,monitorId);
 const profileKey='boat:faturetosl:madtraxbr:companionProfile',snapshotKey='boat:faturetosl:madtraxbr:companionSnapshot',queryKey='boat:faturetosl:madtraxbr:query:profile:';store[profileKey]={name:'madtraxbr',equipment:[{name:'Isca Turbinada',image:'old.png'}]};store[snapshotKey]={profile:store[profileKey]};store[queryKey]={profile:store[profileKey]};const equipment=[{name:'Vara de Carbono',image:'rod.png'},{name:'Anzol (vazio)',icon:'🪝'},{name:'Mochila (vazio)',icon:'🎒'},{name:'Isca (vazio)',image:null,icon:'🪱'}];await send({type:'reading',seconds:120,equipment},{url:tabs.get(monitorId).url,tab:{id:monitorId}});for(const key of [profileKey,snapshotKey,queryKey])assert.equal((store[key].profile||store[key]).equipment[3].name,'Isca (vazio)');await send({type:'reading',seconds:null,error:'Sem leitura',equipment:[]},{url:tabs.get(monitorId).url,tab:{id:monitorId}});assert.equal(store[profileKey].equipment[3].icon,'🪱');
 const liveSnapshot={profile:{name:'madtraxbr',coins:1750,equipment},fish:[{name:'piau',count:2,protected:false}],directSaleTotal:10,at:Date.now()};await send({type:'reading',seconds:120,snapshot:liveSnapshot},{url:tabs.get(monitorId).url,tab:{id:monitorId}});assert.equal(store[snapshotKey].fish[0].name,'piau');assert.equal(store[snapshotKey].directSaleTotal,10);
 tabs.get(1).url='https://www.twitch.tv/midor1yatft';alarmListener({name:'companionOwnedTabs'});await send({type:'monitorHealth'});assert.equal(tabs.size,4);assert.equal(session.companionOwnedChatTab,chatId);assert.equal(session.companionOwnedMonitorTab,monitorId);
 await send({type:'reading',seconds:0,fishProtection:[{name:'jundiá',protected:true},{name:'acará',protected:false}]},{url:tabs.get(monitorId).url,tab:{id:monitorId}});assert.deepEqual(store['boat:faturetosl:madtraxbr:companionSiteProtected'],['jundiá']);await send({type:'reading',seconds:0,fishProtection:[{name:'jundiá',protected:false}]},{url:tabs.get(monitorId).url,tab:{id:monitorId}});assert.deepEqual(store['boat:faturetosl:madtraxbr:companionSiteProtected'],[]);await send({type:'fish',boat:'faturetosl'});assert.equal(keys.filter(m=>m==='submitNative').length,1);assert.equal(keys.filter(m=>m.startsWith('Input.')||m.startsWith('Emulation.')).length,0);assert.equal(tabs.get(1).active,true);
 tabs.get(2).url='https://twish.com.br/c/novobarco/madtraxbr/inventory';const locked=await send({type:'selectBoat'},{url:tabs.get(2).url,tab:{id:2}});assert.equal(locked.contextLocked,true);assert.equal(store.fishState.boat,'faturetosl');assert.match(tabs.get(chatId).url,/popout\/faturetosl\/chat/);store.fishState.enabled=false;await send({type:'selectBoat'},{url:tabs.get(2).url,tab:{id:2}});store.fishState.enabled=true;await send({type:'monitorHealth'});assert.equal(session.companionOwnedChatTab,chatId);assert.equal(session.companionOwnedMonitorTab,monitorId);assert.match(tabs.get(chatId).url,/popout\/novobarco\/chat/);assert.equal(tabs.size,4);
 await send({type:'command',command:'$coins',boat:'novobarco'});assert.equal(keys.filter(m=>m==='submitNative').length,2);assert.equal(tabs.get(1).url,'https://www.twitch.tv/midor1yatft');
 const shopKey='boat:novobarco:madtraxbr:query:shop:';await send({type:'siteQuery',page:'shop',boat:'novobarco'});assert.equal(shopReads,1);await send({type:'siteQuery',page:'shop',boat:'novobarco'});assert.equal(shopReads,1,'Cache da loja reutilizado');store.fishState.event={text:'Desconto na Loja! 20%',seconds:100};let shop=await send({type:'siteQuery',page:'shop',boat:'novobarco'});assert.equal(shopReads,2);assert.equal(shop.items[0].price,4800);store.fishState.event=null;shop=await send({type:'siteQuery',page:'shop',boat:'novobarco'});assert.equal(shopReads,3);assert.equal(shop.items[0].price,6000);assert.equal(store['boat:novobarco:madtraxbr:companionShopBalances'].scales,7);
 fishReply=null;Object.assign(store.fishState,{lastAttempt:0,used:false,at:Date.now(),seconds:0,catchResult:null});await send({type:'fish',boat:'novobarco'});assert.equal(store.fishState.catchResult.error,true);assert.match(store.fishState.catchResult.message,/confirmar o resultado/);assert.notEqual(store.fishState.catchResult.caught,false,'Timeout não significa pesca perdida');
 await send({type:'toggle',enabled:false,boat:'novobarco'});assert.equal(tabs.size,2);assert(tabs.has(1)&&tabs.has(2));await send({type:'monitorHealth'});assert.equal(tabs.size,2);
 console.log('Chat próprio: silencioso, em segundo plano, envio no alvo exclusivo, troca sem duplicar e pausa preservando abas pessoais.');
})();
